<?php
session_start();
require "../fpdf.php";
$pdf = new FPDF();
$db = new PDO("mysql:host=localhost;dbname=db_findmynest","root","");
        $pdf->AddPage('P','A4',0);
        $pdf->Image('../assets/images/main-logo.png',8,8,35);
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(200,25,'Home Loan Application',0,0,'C');
        $pdf->Ln(25);
        $res = "SELECT * FROM `tbl_loanapplication`";
        $result = $db->prepare($res);
        $result->execute();
        while($row = $result->fetch())
        {
        $pdf->SetLeftMargin(20);
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'Name',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['name'],1,0,'L');
        $pdf->Ln();
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'Address',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['address'],1,0,'L');
        $pdf->Ln();
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'State',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['state'],1,0,'L');
        $pdf->Ln();
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'District',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['district'],1,0,'L');
        $pdf->Ln();
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'Mobile',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['mobile'],1,0,'L');
        $pdf->Ln();
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'Email',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['email'],1,0,'L');
        $pdf->Ln();
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'Age',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['age'],1,0,'L');
        $pdf->Ln();
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'Occupation',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['occupation'],1,0,'L');
        $pdf->Ln();
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'Loan Amount',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['loan_amt'],1,0,'L');
        $pdf->Ln();
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'Property Description',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['prop_des'],1,0,'L');
        $pdf->Ln();
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'Bank',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['bank'],1,0,'L');
        $pdf->Ln();
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'Income',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['income'],1,0,'L');
        $pdf->Ln();
        $pdf->SetFont('Times','B',12);
        $pdf->Cell(80,10,'Applied Date',1,0,'L');
        $pdf->SetFont('Times','',12);
        $pdf->Cell(80,10,$row['date'],1,0,'L');
        $pdf->Ln();
        $pdf->SetRightMargin(10);
        }
$pdf->Output();